using mark.davison.common.client.abstractions.Repository;

namespace mark.davison.common.server.integrationtests.Tests.CQRS;

[TestClass]
public class CQRSTests : IntegrationTestBase<SampleApplicationFactory, AppSettings>
{

    [TestMethod]
    public async Task ExampleGetQuery_WorksAsExpected()
    {
        var repository = Services.GetRequiredService<IClientHttpRepository>();
        var request = new ExampleGetRequest
        {
            RequestValue = "sihjbdsfuihjdfsiuhjdfs",
            DateOnlyValue = DateOnly.FromDateTime(DateTime.Now)
        };

        var response = await repository.Get<ExampleGetResponse, ExampleGetRequest>(request, CancellationToken.None);

        Assert.IsNotNull(response);
        Assert.AreEqual(request.RequestValue, response.ResponseValue);
    }


    [TestMethod]
    public async Task ExamplePostQuery_WorksAsExpected()
    {
        var repository = Services.GetRequiredService<IClientHttpRepository>();
        var request = new ExamplePostRequest
        {
            TestEnumValue = TestEnum.ValueThree
        };

        var response = await repository.Post<ExamplePostResponse, ExamplePostRequest>(request, CancellationToken.None);

        Assert.IsNotNull(response);
        Assert.AreEqual(request.TestEnumValue, response.TestEnumValue);
    }

    [TestMethod]
    public async Task ExampleValidateAndProcessQuery_WithAutoGeneratedHandler_Works()
    {
        var repository = Services.GetRequiredService<IClientHttpRepository>();
        var request = new ExampleValidateAndProcessQueryRequest();
        var response = await repository.Get<ExampleValidateAndProcessQueryResponse, ExampleValidateAndProcessQueryRequest>(request, CancellationToken.None);

        Assert.IsNotNull(response);
        Assert.IsTrue(response.Success);
    }

    [TestMethod]
    public async Task ExampleValidateAndProcessCommand_WithAutoGeneratedHandler_Works()
    {
        var repository = Services.GetRequiredService<IClientHttpRepository>();
        var request = new ExampleProcessCommandRequest();
        var response = await repository.Post<ExampleProcessCommandResponse, ExampleProcessCommandRequest>(request, CancellationToken.None);

        Assert.IsNotNull(response);
        Assert.IsTrue(response.Success);
    }
}
